### ISSUE TITLE
Motors buzzing, machine not responding to comands 3018pro

### ISSUE THREAD

**Issue by Igor1311** [grbl/grbl#1758]
Hi guys, 

I am a complete beginer regarding CNC machines. The one i got is 3018 pro. After thinkering a bit with settings etc. Im getting a buzzing noise from motors, but machine is not moving accross any axis, or responding to comands. I am using UGS software.
The buzzing stops once I start homing, but it allways ends with alarm.
This is the Alarm and Error im getting -

**[Error] An error was detected while sending '$H': (ALARM:9) Homing fail. Could not find limit switch within search distances. Try increasing max travel, decreasing pull-off distance, or check wiring. Streaming has been paused.
[Error] Error while processing response : An unexpected command was completed by the controller.**

This is the alarm descripition - 
**com.willwinder.universalgcodesender.AbstractController$UnexpectedCommand: An unexpected command was completed by the controller.
at com.willwinder.universalgcodesender.AbstractController.commandComplete(AbstractController.java:830)
[catch] at com.willwinder.universalgcodesender.GrblController.rawResponseHandler(GrblController.java:158)
at com.willwinder.universalgcodesender.AbstractController.rawResponseListener(AbstractController.java:851)
at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListeners(AbstractCommunicator.java:222)
at com.willwinder.universalgcodesender.AbstractCommunicator.lambda$new$0(AbstractCommunicator.java:244)
at java.lang.Thread.run(Unknown Source)**

My settings are

0 = 10 (Step pulse time, microseconds)
$1 = 25 (Step idle delay, milliseconds)
$2 = 0 (Step pulse invert, mask)
$3 = 0 (Step direction invert, mask)
$4 = 1 (Invert step enable pin, boolean)
$5 = 0 (Invert limit pins, boolean)
$6 = 0 (Invert probe pin, boolean)
$10 = 115 (Status report options, mask)
$11 = 0.010 (Junction deviation, millimeters)
$12 = 0.002 (Arc tolerance, millimeters)
$13 = 0 (Report in inches, boolean)
$20 = 0 (Soft limits enable, boolean)
$21 = 1 (Hard limits enable, boolean)
$22 = 1 (Homing cycle enable, boolean)
$23 = 0 (Homing direction invert, mask)
$24 = 25.000 (Homing locate feed rate, mm/min)
$25 = 500.000 (Homing search seek rate, mm/min)
$26 = 250 (Homing switch debounce delay, milliseconds)
$27 = 1.000 (Homing switch pull-off distance, millimeters)
$30 = 1000 (Maximum spindle speed, RPM)
$31 = 0 (Minimum spindle speed, RPM)
$32 = 0 (Laser-mode enable, boolean)
$100 = 800.000 (X-axis travel resolution, step/mm)
$101 = 800.000 (Y-axis travel resolution, step/mm)
$102 = 800.000 (Z-axis travel resolution, step/mm)
$110 = 1600.000 (X-axis maximum rate, mm/min)
$111 = 1600.000 (Y-axis maximum rate, mm/min)
$112 = 100.000 (Z-axis maximum rate, mm/min)
$120 = 20.000 (X-axis acceleration, mm/sec^2)
$121 = 20.000 (Y-axis acceleration, mm/sec^2)
$122 = 20.000 (Z-axis acceleration, mm/sec^2)
$130 = 300.000 (X-axis maximum travel, millimeters)
$131 = 180.000 (Y-axis maximum travel, millimeters)
$132 = 45.000 (Z-axis maximum travel, millimeters)

Any chance you could help me with this one?

**Comment by DM-Anthony** [comment]
Your config says you have $2=0 and $3=0 the same value. that cannot happen the motors wouldnt move...  $10=cannot be 115 because it does not exist. $20=0 your soft limits are not enabled, hard stop end of work area is enabled
